"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { ArrowLeft, Send, Loader2, Copy, Check } from "lucide-react"
import Link from "next/link"
import { toast } from "sonner"

// DMCA Notice Template
const generateDMCANotice = (data: {
    ownerName: string
    contentTitle: string
    originalUrl: string
    infringingUrl: string
    date: string
}) => `
DMCA TAKEDOWN NOTICE

Date: ${data.date}

To Whom It May Concern:

I am writing to notify you of copyright infringement on your platform.

1. IDENTIFICATION OF COPYRIGHTED WORK:
   Title: ${data.contentTitle}
   Original URL: ${data.originalUrl}

2. IDENTIFICATION OF INFRINGING MATERIAL:
   Infringing URL: ${data.infringingUrl}

3. CONTACT INFORMATION:
   Name: ${data.ownerName}
   This notice is sent via PirateSlayer (https://pirateslayer.com)

4. GOOD FAITH STATEMENT:
   I have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.

5. ACCURACY STATEMENT:
   I swear, under penalty of perjury, that the information in this notification is accurate and that I am the copyright owner, or am authorized to act on behalf of the owner, of an exclusive right that is allegedly infringed.

6. REQUEST FOR REMOVAL:
   I hereby request that you immediately remove or disable access to the infringing material identified above.

Sincerely,
${data.ownerName}
---
Generated by PirateSlayer - Protect Your Digital Content
`

interface PageProps {
    params: Promise<{ id: string }>
}

export default function SendDMCAPage({ params }: PageProps) {
    const router = useRouter()
    const [loading, setLoading] = useState(false)
    const [copied, setCopied] = useState(false)
    const [ownerName, setOwnerName] = useState("")

    // Generate notice preview
    const notice = generateDMCANotice({
        ownerName: ownerName || "[Your Name]",
        contentTitle: "Your Protected Content",
        originalUrl: "https://your-course-url.com",
        infringingUrl: "Loading...",
        date: new Date().toLocaleDateString()
    })

    const handleCopy = () => {
        navigator.clipboard.writeText(notice)
        setCopied(true)
        toast.success("DMCA notice copied to clipboard!")
        setTimeout(() => setCopied(false), 2000)
    }

    const handleSend = async () => {
        if (!ownerName) {
            toast.error("Please enter your name")
            return
        }

        setLoading(true)
        try {
            // In production, this would send the email via API
            toast.success("DMCA notice sent successfully!")
            router.push("/dashboard/takedowns")
        } catch (error) {
            toast.error("Failed to send DMCA notice")
        } finally {
            setLoading(false)
        }
    }

    return (
        <div className="max-w-3xl mx-auto space-y-6">
            {/* Header */}
            <div className="flex items-center gap-4">
                <Button asChild variant="ghost" size="icon" className="text-slate-400 hover:text-white">
                    <Link href="/dashboard/takedowns">
                        <ArrowLeft className="w-5 h-5" />
                    </Link>
                </Button>
                <div>
                    <h1 className="text-2xl font-bold text-white">Send DMCA Notice</h1>
                    <p className="text-slate-400 mt-1">
                        Generate and send a legally-compliant takedown request
                    </p>
                </div>
            </div>

            {/* Your Information */}
            <Card className="bg-slate-900 border-slate-800">
                <CardHeader>
                    <CardTitle className="text-white">Your Information</CardTitle>
                    <CardDescription className="text-slate-400">
                        This will appear in the DMCA notice
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <input
                        type="text"
                        placeholder="Your Full Legal Name"
                        value={ownerName}
                        onChange={(e) => setOwnerName(e.target.value)}
                        className="w-full p-3 rounded-lg bg-slate-800 border border-slate-700 text-white placeholder:text-slate-500"
                    />
                </CardContent>
            </Card>

            {/* DMCA Preview */}
            <Card className="bg-slate-900 border-slate-800">
                <CardHeader>
                    <CardTitle className="text-white">DMCA Notice Preview</CardTitle>
                    <CardDescription className="text-slate-400">
                        Review the notice before sending
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <Textarea
                        value={notice}
                        readOnly
                        className="bg-slate-800 border-slate-700 text-slate-300 font-mono text-sm min-h-[400px]"
                    />
                </CardContent>
            </Card>

            {/* Actions */}
            <div className="flex gap-4">
                <Button
                    variant="outline"
                    onClick={handleCopy}
                    className="flex-1 border-slate-700 text-slate-300 hover:bg-slate-800"
                >
                    {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
                    {copied ? "Copied!" : "Copy to Clipboard"}
                </Button>
                <Button
                    onClick={handleSend}
                    disabled={loading || !ownerName}
                    className="flex-1 bg-red-600 hover:bg-red-700"
                >
                    {loading && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                    <Send className="w-4 h-4 mr-2" />
                    Send DMCA Notice
                </Button>
            </div>
        </div>
    )
}
